### ISSUE TITLE
addListener() cant listening when change gps from method openSettings()

### ISSUE THREAD

**Issue by havinhthai** [neuberoliveira/react-native-gps-state#11]
## Version
react: 16.3.1
react-native: 0.55.4
react-native-gps-state: 0.0.2

## Issue
Method addListener() not working when I enable/disable GPS via openSettings()

**Comment by neuberoliveira** [comment]
This plugin was originaly developed to RN 0.45, i not test it in recent versions.

I did this project because I could not find any that fit my needs for a larger project. Now I know there is a better project that do pretty the same, and more, its called: react-native-permissions

So as you can see this repository is virtually abandoned.
