### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by RameshkrishnanV** [neuberoliveira/react-native-gps-state#12]
Hi Thanks for the plugin,

     I'm facing this issue while linking with my react native app.
  
    RN - 0.55

Please help.

**Comment by neuberoliveira** [comment]
This plugin was originaly developed  to RN 0.45, i not test it in recent versions.

I did this project because I could not find any that fit my needs for a larger project. Now I know there is a better project that do pretty the same, and more, its called: [react-native-permissions](https://github.com/yonahforst/react-native-permissions)

So as you can see this repository is virtually abandoned.
