### ISSUE TITLE
Error while building for android [com.android.tools.build:gradle version not available]

### ISSUE THREAD

**Issue by dopey2** [neuberoliveira/react-native-gps-state#15]
I have an error when I try to build for android:

`could not find any matches for com.android.tools.build:gradle:2.2.+ as no versions of com.android.tools.build:gradle are available.
Searched in the following locations:
         https://jcenter.bintray.com/com/android/tools/build/gradle/maven-metadata.xml
         https://jcenter.bintray.com/com/android/tools/build/gradle/
     Required by:
         project :react-native-gps-state`

The library uses an old version of Gradle that is not available in the jcenter repository

` dependencies {
        classpath 'com.android.tools.build:gradle:2.2.+'
    }
`

## Environment
react-native: 0.57.2
react-native-gps-state: 0.1.2

Can you please remove that dependency?
The lib will simply be built using the parent project's Gradle version.

**Comment by neuberoliveira** [comment]
Try to remove the package from your project, today i got the same error but in another lib, my case is `react-native-vector-icons`. I try without the gps-state plugin and got the same error, i will investigate a bit more.

**Comment by neuberoliveira** [comment]
The problem is not exactly related with `gps-state` i got the same error with these libraries too
`react-native-vector-icons` and `react-native-image-picker`

For me the error is on the `jcenter` side, as your logs points out (and mine too) it cant find the metadata xml located at `https://jcenter.bintray.com/com/android/tools/build/gradle/maven-metadata.xml`.

All the problematic libs (including gps-state) have a `+` on the gradle version, so i suppose the info about latest version is in that `maven-metadata.xml`, as long it not exists there's no way to figure out the version, hence the error.

As a temp fix, change this `2.2.+` to `2.2.2` (can't remember exactly, what is the version) and things back to work again.

I will close this, but feel free to reopen it if necessary.

**Comment by adirzoari** [comment]
same issue. did you find any solution? @neuberoliveira  @mtebele  @dopey2

**Comment by dopey2** [comment]
@adirzoari  it works fine for me if i remove that dependency

**Comment by mujeebrahaman** [comment]
still facing same issue, pls change gradle version to 2.2.3, it will work fine, as i raised pull request please merge it ASAP

**Comment by neuberoliveira** [comment]
@adirzoari @dopey2 @mujeebrahaman released version 1.2.1 that fix this.

By the way iam planing to release the version 2.0.0 this week, it will come with a lot of improvements so stay tuned for updates.

**Comment by hielfx** [comment]
I'ms still getting the error, but now with the new version (2.2.3). It seems it has been removed from the jcenter repository; [this stack overflow answer](https://stackoverflow.com/a/53716590) helped me in order to get the project working back again. Hope that helps others looking for this issue.

Maybe it could be added to the Readme or change the repository url in your dependency @neuberoliveira

**Comment by neuberoliveira** [comment]
@mujeebrahaman you still able to compile with 2.2.3 ??

@hielfx iam in the proccess of release of version 2. Iam using version `2.3.3` with my `APP_ROOT/android/gradle/wrapper/gradle-wrapper.properties` set to `distributionUrl=https\://services.gradle.org/distributions/gradle-3.5.1-all.zip`. If you could give it a try i will be glad.

**Comment by mujeebrahaman** [comment]
@neuberoliveira  yes

**Comment by hielfx** [comment]
@neuberoliveira In my project I'm using `distributionUrl=https\://services.gradle.org/distributions/gradle-4.1-all.zip` (I can't downgrade it more). I've tried to change the dependency classpath to `com.android.tools.build:gradle:2.3.3` inside node_modules with no use: still getting the jcenter error.

Do you want me to include the fix in a pr meanwhile you release the v2.0.0?

**Comment by neuberoliveira** [comment]
@hielfx take a look at this link [about gradle versions map](https://developer.android.com/studio/releases/gradle-plugin#updating-gradle) seems 2.3.3 is not supported by gradle-4.1 

I really dont know how to solve this. in gradle-4.1 they replace the `compile` with `implementation`, and other things. So if i release an update to gradle 4.1 those who use 3.5.1 will have issues about `implementation` method not exists.

maybe if i release a version 2 and next a version 3 with support for 4.1 ? Seems a good ideia?

**Comment by codlab** [comment]
the best practice in this case is to remove every specific gradle information. From the Android documentation, the common practice should be to use the "new standard" rootProject.ext, removing every specific gradle dependencies (compile is deprecated, when it will be removed completely, the update should be quite easy)

For instance, here is the modification in the fork I made to help upgrade to the 28th revisions of the libraries as well as gradle 4.10+ (for instance)

[https://github.com/codlab/react-native-gps-state/blob/impr/gradle/android/build.gradle](https://github.com/codlab/react-native-gps-state/blob/impr/gradle/android/build.gradle)

Every libraries "should" use such tip. cf. : [https://developer.android.com/studio/build/gradle-tips](https://developer.android.com/studio/build/gradle-tips)
