### ISSUE TITLE
Upload latest version to npmjs

### ISSUE THREAD

**Issue by mtebele** [neuberoliveira/react-native-gps-state#5]
Hi! Could you make a release and upload a new version to [npmjs](https://www.npmjs.com/package/react-native-gps-state)?

**Comment by neuberoliveira** [comment]
I did this project because I could not find any that fit my needs for a larger project. Now I know there is a better project that do pretty the same, and more, its called: [react-native-permissions](https://github.com/yonahforst/react-native-permissions)

So as you can see this repository is virtually abandoned. I will try to maintain it but no guarantees.

Too late i think but the new version is published. If something goes bad ill try to help.
