### ISSUE TITLE
can not find symbol GPSStatePackage

### ISSUE THREAD

**Issue by charlie0275** [neuberoliveira/react-native-gps-state#7]
cannot find symbol
          new GPSStatePackage()
              ^
symbol: class GPSStatePackage
errors
app:compileDebugJavaWithJavac FAILED

**Comment by AndreWerdan** [comment]
have same problem

**Comment by aperhaite** [comment]
This error occurs because the `react-native link react-native-gps-state` doesn't work fine. You can do a manual setup:

#### Android

**android/settings.gradle**

```gradle
include ':react-native-gps-state'
project(':react-native-gps-state').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-gps-state/android')
```

**android/app/build.gradle**

```gradle
dependencies {
   ...
   compile project(':react-native-gps-state')
}
```

**MainApplication.java**

On top, where imports are:

```java
import br.com.dopaminamob.gpsstate.GPSStatePackage;
```

Add the `new GPSStatePackage()` class to your list of exported packages.

```java
@Override
protected List<ReactPackage> getPackages() {
    return Arrays.asList(
            new MainReactPackage(),
            new GPSStatePackage(),
    );
}
```

If the build fails again, remove `android:allowBackup="false"` from `AndroidManifest.xml`

**Comment by umerbaig** [comment]
I'm getting `Error:(20, 35) error: package br.com.dopaminamob.gpsstate does not exist`

**Comment by neuberoliveira** [comment]
Ages later but thanks @aperhaite
