### ISSUE TITLE
To get the library working need to remove "@Override" in GPSStatePackage.java

### ISSUE THREAD

**Issue by dinukasal** [neuberoliveira/react-native-gps-state#8]
My package versions,

    "react": "16.2.0",
    "react-native": "0.52.0",

I had to comment the line "@Overrides" 
`	
// @Override 

	public List<Class<? extends JavaScriptModule>> createJSModules() {
		return Collections.emptyList();
	}`

to get the library working.

**Comment by janakact** [comment]
+1

**Comment by janakact** [comment]
The bug seems to be already fixed here. Can someone do a release? @neuberoliveira  ^_^ 
https://github.com/neuberoliveira/react-native-gps-state/commit/00264afd95c8c107d8755146efc1d4a41508dcb1#diff-03c73154f539cd29e74eb71e508649b0

**Comment by havinhthai** [comment]
+1 Same issue

**Comment by neuberoliveira** [comment]
This plugin was originaly developed  to RN 0.45, i not test it in recent versions.

I did this project because I could not find any that fit my needs for a larger project. Now I know there is a better project that do pretty the same, and more, its called: [react-native-permissions](https://github.com/yonahforst/react-native-permissions)

So as you can see this repository is virtually abandoned. I will try to maintain it but no guarantees.

Too late i think but the new version is published. If something goes bad ill try to help.
